version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    links:
      - api
      - mongo

  api:
    image: is-api
    container_name: is-api
    depends_on:
      - mongo
    ports:
<<<<<<< HEAD
      - "3000:8080"
=======
      - "8080:8080"
>>>>>>> ff6a86bbff0fa4c9e4f6b00f4da0dc0aa8bc6abf
    environment:
      - VIRTUAL_HOST=local.host
    volumes:
      - /home/jorge/public/upload:/usr/src/app/upload


  mongo:
    image: mongodb
    container_name: is-db
    ports:
      - "27017:27017"
